name: Build and Deploy

on:
  push:
    branches:
      - zadanie10-punkt2
  pull_request:
    branches:
      - zadanie10-punkt2
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR Public
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and push server image
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: public.ecr.aws/e8m0n2w8/lab10-server:latest

      - name: Build and push client image
        uses: docker/build-push-action@v2
        with:
          context: ./simple-client
          file: ./simple-client/Dockerfile
          push: true
          tags: public.ecr.aws/e8m0n2w8/lab10-client:latest
